halstack-browser repo is up to date OC-12874
dxc-technology/dxc-halstack-browser pull request #4
Opened 2022-11-25 10:06 UTC by kukoc

https://jira.dxc.com/browse/OC-12874

- Refactor of the library replacing @diaas/api-sdk by halstack-client
- Github actions:
        - Publish next version  
        - Publish release 
        - build and test on PR
        - HalUI COmponent test

2022-11-25 10:29 UTC, marcialfps requested changes
- Why do you have a `yarn.lock` file in the example directory?

2022-11-25 10:29 UTC, marcialfps commented on .github/workflows/publish-next.yml
> +      - aef-actions
Change to `master`.

2022-11-25 10:29 UTC, marcialfps commented on example/src/App.js
> +const YOUR_API_KEY = 'RlbIOdmhnj9Pd85G8fwFA5fdJWYcXtHq7my0wNa1'; // From DXC Developer Central
I think the API key is private, you should remove it.

2022-11-25 10:29 UTC, marcialfps commented on lib/README.md
> +npm install --save TBD
Change `TBD`.

2022-11-25 10:29 UTC, marcialfps commented on lib/README.md
> +git clone https://github.dxc.com/DIaaS/diaas-hal-ui.git
Change repository url.

2022-11-25 10:29 UTC, marcialfps commented on lib/src/hal-ui/HalUI.jsx
> +    /*axios({
Remove unused code.

2022-11-25 10:29 UTC, marcialfps commented on lib/src/hal-ui/Operation.jsx
> +//import axios from "axios";
Remove import.

2022-11-25 10:29 UTC, marcialfps commented on lib/src/hal-ui/Operation.jsx
> +    /*axios({
Remove unused code.

2022-11-25 10:29 UTC, marcialfps commented on lib/testingActions.md
> +X
This is a file for testing purposes, so you need to remove it before merging.

2022-11-28 10:24 UTC, kukoc commented
> * Why do you have a `yarn.lock` file in the example directory?

I think we should keep the lock files so the security bots can do a better job scanning vulnerabilities.

2022-12-20 10:47 UTC, marcialfps requested changes

2022-12-20 10:47 UTC, marcialfps commented on example/src/App.js
> +//import HalUI from "./hal/hal-ui/HalUI";
Remove this comment.

2022-12-20 10:47 UTC, marcialfps commented on lib/README.md
> +npm install @diaas/hal-browser --save
Change to `@dxc-technology/halstack-browser`

2022-12-20 10:47 UTC, marcialfps commented on lib/README.md
> +import HalUI from "@diaas/hal-browser";
Change to `@dxc-technology/halstack-browser`

2022-12-20 13:55 UTC, marcialfps approved these changes
💯

2022-12-20 13:55 UTC, merged